name: Install linting tools
description: "A reusable action to install linting tools"
runs:
  using: "composite"
  steps:
    - name: Set up python 3.11
      uses: actions/setup-python@v4
      with:
        cache: "pip"
        python-version: "3.11"
    - name: Install dependencies
      shell: bash
      run: |
        make install-ci
        make install-lint
