name: Pipeline

on:
  push:

jobs:

  # Lint

  check-ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/lint-install
      - name: Run ruff
        run: |
          make check-ruff

  check-black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/lint-install
      - name: Run black
        run: |
          make check-black

  check-isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/lint-install
      - name: Run isort
        run: |
          make check-isort

  check-mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/lint-install
      - name: Run mypy
        run: |
          make check-mypy

  check-pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/lint-install
      - name: Install dependencies
        run: |
          make install-dev SYNC=""
      - name: Run pylint
        run: |
          make check-pylint

  # Test

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
          cache: "pip"
          python-version: "3.11"
      - name: Install dependencies
        run: |
          make install-ci SYNC=""
          make install-test
      - name: Run tests
        run: |
          make test
